# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 18:27
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import trix.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_publicacion', model_utils.fields.MonitorField(default=django.utils.timezone.now, editable=False, monitor='estado', when=set(['publicado']))),
                ('título', models.CharField(max_length=100)),
                ('fecha', models.DateField(default=datetime.date(2017, 4, 15))),
                ('declaración', trix.fields.TrixField()),
                ('estado', model_utils.fields.StatusField(choices=[('borrador', 'borrador'), ('publicado', 'publicado')], default='borrador', max_length=100, no_check_for_status=True)),
                ('nota_interna', models.TextField(blank=True, null=True)),
                ('cargado_por', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
