# Generated by Django 2.2 on 2019-09-02 23:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterModelOptions(
            name='declaracion',
            options={'ordering': ('estado', '-fecha', '-id')},
        ),
        migrations.AlterField(
            model_name='declaracion',
            name='fecha',
            field=models.DateField(default=datetime.date(2019, 9, 2)),
        ),
        migrations.AddField(
            model_name='declaracion',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='declaracion.Template'),
        ),
    ]
