# Generated by Django 2.2 on 2019-09-03 00:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0002_auto_20190902_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaracion',
            name='fecha',
            field=models.DateField(default=datetime.date(2019, 9, 3)),
        ),
    ]
