# Generated by Django 2.2 on 2019-09-05 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0004_auto_20190904_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaracion',
            name='fecha',
            field=models.DateField(default=datetime.date(2019, 9, 5)),
        ),
    ]
