# Generated by Django 2.2 on 2019-09-18 22:16

import datetime
from django.db import migrations, models
import trix.fields


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0005_auto_20190905_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='archivo',
        ),
        migrations.AddField(
            model_name='template',
            name='contenido',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='contenido_extra',
            field=trix.fields.TrixField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='declaracion',
            name='fecha',
            field=models.DateField(default=datetime.date(2019, 9, 18)),
        ),
    ]
