# Generated by Django 2.2 on 2019-09-18 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0006_auto_20190918_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='contenido_extra',
        ),
    ]
