# Generated by Django 2.2 on 2019-11-06 22:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('declaracion', '0008_auto_20191002_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='groups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='declaracion',
            name='fecha',
            field=models.DateField(default=datetime.date(2019, 11, 6)),
        ),
    ]
